  var a = [{"color":"#A167A5","id":1,"tags":["rearly purle"]},
	{"color":"#CD5334","id":2,"tags":["dark coral","warm"]},
	{"color":"#17BEBB","id":3,"tags":["tiffany blue","cold"]},
	{"color":"#CEFF1A","id":4,"tags":["artic lime","warm"]},
	{"color":"#00171F","id":5,"tags":["rich black","dark"]},
	{"color":"#FFED66","id":6,"tags":["maize"]},
	{"color":"#7B886F","id":7,"tags":["camouflage green"]},
	{"color":"#FFBCB5","id":8,"tags":["melon"]},
	{"color":"#FE9920","id":9,"tags":["deep saffron","warm"]},
	{"color":"#D6EFFF","id":10,"tags":["azureish white","cold"]},
	{"color":"#6D213C","id":11,"tags":["wine"]},
	{"color":"#2E294E","id":12,"tags":["space cadet","cold","dark"]},
	{"color":"#E3C16F","id":13,"tags":["straw"]},
	{"color":"#5D3A00","id":14,"tags":["seal brown"]},
	{"color":"#F9B9F2","id":15,"tags":["electric lavender"]},
	{"color":"#4C5F6B","id":16,"tags":["deep space sparkle"]},
	{"color":"#BED558","id":17,"tags":["june bud"]},
	{"color":"#9FFCDF","id":18,"tags":["magic mint"]},
	{"color":"#91C499","id":19,"tags":["eton blue"]},
	{"color":"#247BA0","id":20,"tags":["lapis lazuli","cold"]}];
 export default a 